### ISSUE TITLE
`pip install -e .` not working

### ISSUE THREAD

**Issue by PhilipMay** [telekom/nlu-bridge#8]
To develop this package I would like to install it in `-e` mode with: `pip install -e .` - but this is not working.

```
$  conda activate nlu-bridge-dev
$ pip install -e .
Obtaining file:///home/mike/dev/fork/nlu-bridge
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: nlubridge
  Running setup.py develop for nlubridge
    ERROR: Command errored out with exit status 1:
     command: /home/mike/miniconda3/envs/nlu-bridge-dev/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mike/dev/fork/nlu-bridge/setup.py'"'"'; __file__='"'"'/home/mike/dev/fork/nlu-bridge/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/mike/dev/fork/nlu-bridge/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mike/miniconda3/envs/nlu-bridge-dev/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mike/dev/fork/nlu-bridge/setup.py'"'"'; __file__='"'"'/home/mike/dev/fork/nlu-bridge/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
(nlu-bridge-dev) [mike@manpad nlu-bridge]$ pip install setuptools
Requirement already satisfied: setuptools in /home/mike/miniconda3/envs/nlu-bridge-dev/lib/python3.8/site-packages (58.0.4)
(nlu-bridge-dev) [mike@manpad nlu-bridge]$ pip install -e .
Obtaining file:///home/mike/dev/fork/nlu-bridge
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: nlubridge
  Running setup.py develop for nlubridge
    ERROR: Command errored out with exit status 1:
     command: /home/mike/miniconda3/envs/nlu-bridge-dev/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mike/dev/fork/nlu-bridge/setup.py'"'"'; __file__='"'"'/home/mike/dev/fork/nlu-bridge/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/mike/dev/fork/nlu-bridge/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/mike/miniconda3/envs/nlu-bridge-dev/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/mike/dev/fork/nlu-bridge/setup.py'"'"'; __file__='"'"'/home/mike/dev/fork/nlu-bridge/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

setuptools is installed btw.

```
$ pip list
Package    Version
---------- ---------
certifi    2021.10.8
pip        21.2.4
setuptools 58.0.4
wheel      0.37.1
```

**Comment by Ablesius** [comment]
In the current version, there is no `setup.py`, so editable mode is disabled by pip itself:

```
[I] alex@devlaptop ~/C/nlu-bridge (fix-install)> pip install -e .
Defaulting to user installation because normal site-packages is not writeable
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/alex/Code/nlu-bridge
(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)
```

The `setup.py` was removed with commit d9edcd527b64a54b34fc9aea2131b62e1a0e8399, but I don't understand why (commit message unfortunately doesn't mention this). @kengelbrecht?

**Comment by kengelbrecht** [comment]
I replaced it with the pyproject.toml, following some tutorial how to publish the package on PyPI. I replaced setup.py instead of just adding pyproject.toml to avoid duplication of code. I wasn't aware editable install does not work with pyproject.toml, but I agree it should be supported. I would be interested what's the best practice for this in your opinion.

**Comment by PhilipMay** [comment]
>  I would be interested what's the best practice for this in your opinion.

My best practice is here: https://github.com/telekom/HPOflow

**Comment by Ablesius** [comment]
I believe going without a `setup.py` and only using `pyproject.toml` doesn't work with `pip install -e` yet. The idea to not want to duplicate code is definitely useful and I've done the same thing in my own packages. Now I'm wondering how I got around the need for `setup.py` myself.

What is the benefit of -e installation when you can also clone the repo from GH?

**Comment by PhilipMay** [comment]
`-e` means the code is installed and linked.
So if you make a change to your code it becomes active without reinstalling.
